services:
  - type: web
    name: verdu-panol
    runtime: docker
    plan: free
    rootDir: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /index.html
    autoDeploy: true
    envVars:
      - key: APP_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false